### ISSUE TITLE
备份链接，直接克隆的作者的网站

### ISSUE THREAD

**Issue by liuzhijie443** [sdjdd/whitewash-torrent#2]
http://1106228663.gearhostpreview.com/bt/
跟作者的效果一样，直接复制的没有改动

**Comment by sdjdd** [comment]
@liuzhijie443 他那个网站去掉 /bt 后跳转到B站了，我也搞不清楚这到底是个啥网站。而且这个项目只是我学习 Vue 的练手项目，随他去吧。。。
